import type { Meta, StoryObj } from '@storybook/html-vite';
import { GateAnimator } from '../animation/GateAnimator';
import { Gate } from '../primitives/gate/Gate';
import { ATLASSIAN_KINDS, JOB_KINDS } from '../primitives/node/emblems';
import { FACE_CAMERA } from '../stage/spawnDrone';
import { specimenStage } from '../stage/specimen';
import type { Stage } from '../stage/Stage';
import { Vector3 } from 'three';
import { ACT1_GATE, ACT1_MAP, ATLASSIAN_GATE, ATLASSIAN_MAP, STORY_CENTER } from './layout';
import { SystemMap } from './SystemMap';

const meta: Meta = {
  title: 'Story/07 Two Systems',
  parameters: { layout: 'fullscreen' },
};
export default meta;

function gateAt(stage: Stage, position: typeof ACT1_GATE): Gate {
  const gate = new Gate({ state: 'open' });
  gate.position.copy(position);
  gate.rotation.y = FACE_CAMERA;
  const animator = new GateAnimator(gate);
  stage.add(gate);
  stage.onTick((dt) => animator.update(dt));
  return gate;
}

/**
 * Layout check: Act 1's system (Figma, GitHub, Notion) and the Atlassian
 * system (Code search, Confluence, Jira, Bitbucket) side by side on the one
 * grid, both fully revealed.
 */
export const Layout: StoryObj = {
  render: () => {
    const { root, stage } = specimenStage({ viewSize: 18.5, focusY: 0 });
    stage.centerOn(STORY_CENTER);
    new SystemMap(stage, gateAt(stage, ACT1_GATE), JOB_KINDS, ACT1_MAP).showAll();
    new SystemMap(stage, gateAt(stage, ATLASSIAN_GATE), ATLASSIAN_KINDS, ATLASSIAN_MAP).showAll();
    return root;
  },
};

/**
 * Procedural layout check: the same four systems around six gates, each with
 * its own seed. Every map is generated by the one rule (see radialMap), so
 * each comes out different, and none can form a pinwheel (see gridRoute).
 */
export const Seeds: StoryObj = {
  render: () => {
    const { root, stage } = specimenStage({ viewSize: 30, focusY: 0 });
    const gates: Vector3[] = [];
    for (let row = 0; row < 2; row++)
      for (let col = 0; col < 3; col++) gates.push(new Vector3(col * 11 - row * 11, 0, -col * 11 - row * 11));
    stage.centerOn(gates.reduce((sum, g) => sum.add(g), new Vector3()).divideScalar(gates.length));
    gates.forEach((at, seed) => new SystemMap(stage, gateAt(stage, at), ATLASSIAN_KINDS, { seed: seed + 1 }).showAll());
    return root;
  },
};
